'use strict';
const fs = require('fs');
const path = require('path');

const CATEGORIES = ['topics', 'sessions', 'snapshots'];
const HEADER_COMMENT = '<!-- generated by tools/memory.js — do not edit by hand -->';

const COMPLEXITY_REGEX = /<!--\s*complexity:\s*(low|medium|high)\s*-->/i;

const BADGE_FOR = { low: '○', medium: '◐', high: '●' };

function badgeFor(entry) {
  if (entry.category === 'sessions' || entry.category === 'snapshots') return '◐';
  if (entry.category === 'topics' && entry.complexity) {
    return BADGE_FOR[entry.complexity];
  }
  return null;
}

function parseComplexity(content) {
  const m = content.match(COMPLEXITY_REGEX);
  return m ? m[1].toLowerCase() : null;
}

function extractHeadBody(content) {
  const lines = content.split('\n');
  let pastH1 = false;
  const body = [];
  for (const line of lines) {
    if (!pastH1) {
      if (line.startsWith('# ')) pastH1 = true;
      continue;
    }
    if (!line.trim()) continue; // whitespace-only
    if (line.trim().startsWith('<!--') && line.trim().endsWith('-->')) continue; // HTML comment line
    body.push(line);
    if (body.length >= 5) break;
  }
  return body.join('\n');
}

function readEntries(root) {
  const memoryDir = path.join(root, 'docs', 'memory');
  if (!fs.existsSync(memoryDir)) return [];
  const entries = [];
  for (const cat of CATEGORIES) {
    const dir = path.join(memoryDir, cat);
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir)) {
      if (!f.endsWith('.md')) continue;
      const filePath = path.join(dir, f);
      const content = fs.readFileSync(filePath, 'utf8');
      const titleMatch = content.match(/^# (.+?)\s*$/m);
      const title = titleMatch ? titleMatch[1] : f.replace(/\.md$/, '');
      const dateMatch = f.match(/^(\d{4}-\d{2}-\d{2})/);
      entries.push({
        category: cat,
        title,
        file: path.relative(root, filePath).replace(/\\/g, '/'),
        date: dateMatch ? dateMatch[1] : null,
        complexity: parseComplexity(content),
        headBody: extractHeadBody(content),
      });
    }
  }
  return entries;
}

function renderIndex(entries) {
  const groups = { topics: [], sessions: [], snapshots: [] };
  for (const e of entries) {
    if (groups[e.category]) groups[e.category].push(e);
  }
  groups.topics.sort((a, b) => a.title.localeCompare(b.title));
  groups.sessions.sort((a, b) => (b.date || '').localeCompare(a.date || ''));
  groups.snapshots.sort((a, b) => (b.date || '').localeCompare(a.date || ''));

  const lines = [
    HEADER_COMMENT,
    '',
    '# MEMORY.md',
    '',
    'Persistent semantic knowledge base. Topic files in `docs/memory/`. Updated automatically by `generate-plan.js`.',
    '',
    '**Complexity badges:** ○ low → haiku · ◐ medium → sonnet · ● high → sonnet · (no badge) unknown',
    '',
  ];

  const sectionHeading = { topics: 'Topics', sessions: 'Sessions', snapshots: 'Snapshots' };
  for (const cat of CATEGORIES) {
    const items = groups[cat];
    if (items.length === 0) continue;
    lines.push(`## ${sectionHeading[cat]}`, '');
    for (const e of items) {
      const badge = badgeFor(e);
      const badgePrefix = badge ? `${badge} ` : '';
      const dateSuffix = e.date ? ` · ${e.date}` : '';
      lines.push(`- ${badgePrefix}[${e.title}](${e.file})${dateSuffix}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function compactMemory(opts) {
  const { root } = opts;
  const entries = readEntries(root);
  if (entries.length === 0) return;
  const text = renderIndex(entries);
  fs.writeFileSync(path.join(root, 'MEMORY.md'), text + '\n');
}

module.exports = { renderIndex, compactMemory, readEntries };
