#!/usr/bin/env bash
# One-command local start.
#   ./run.sh         run the server in Docker on port 8080
#   ./run.sh --dev   run the server with tsx watch, no Docker (needs Node >= 22 and pnpm)
#   ./run.sh --help  show this help
set -euo pipefail
cd "$(dirname "$0")"

usage() {
  cat <<'USAGE'
usage: ./run.sh [--dev | --help]

  (no flag)  build and run the server in Docker (docker compose), port 8080
  --dev      run the server directly with tsx watch (needs Node >= 22 and pnpm)
  --help     show this help

Environment: HOST_PORT changes the host-side port for the Docker start (default 8080).
Settings come from .env (created from .env.example on first run).
USAGE
}

die() { echo "error: $*" >&2; exit 1; }

mode="docker"
case "${1:-}" in
  "") ;;
  --dev) mode="dev" ;;
  -h|--help) usage; exit 0 ;;
  *) usage >&2; die "unknown argument: $1" ;;
esac
[ "$#" -le 1 ] || { usage >&2; die "too many arguments"; }

# A random facilitator token, 48 hex characters. Prefers openssl; falls back to /dev/urandom. Never printed.
generate_token() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 24
  else LC_ALL=C od -An -N24 -tx1 /dev/urandom | tr -d ' \n'; fi
}

# Only a NEW .env gets a token: an existing .env (and any token already in it) is never touched, and a symlink named .env is never written through.
# A token counts as set only when it has a value (FACILITATOR_TOKEN= and FACILITATOR_TOKEN="" are unset, as the app's own parser reads them).
token_pat='^[[:space:]]*(export[[:space:]]+)?FACILITATOR_TOKEN[[:space:]]*=[[:space:]]*(["'"'"'][^"'"'"']|[^[:space:]"'"'"'#])'
if [ -L .env ]; then
  echo "warning: .env is a symbolic link, so run.sh leaves it alone and cannot add a facilitator token; make sure its target sets FACILITATOR_TOKEN (see docs/THREAT_MODEL.md)" >&2
elif [ ! -e .env ]; then
  # Generate the token first, build the file privately (mode 600 from creation) and move it into place in one step.
  token="$(generate_token)"
  [ "${#token}" -ge 16 ] || die "could not generate a facilitator token"
  tmp_env="$(umask 077; mktemp ./.env.new.XXXXXX)" || die "could not create a temporary .env"
  trap 'rm -f "$tmp_env"' EXIT
  trap 'rm -f "$tmp_env"; exit 130' INT
  trap 'rm -f "$tmp_env"; exit 143' TERM
  { cat .env.example; printf '\n# Generated by run.sh: facilitators must present this token (see docs/THREAT_MODEL.md). Keep this file private.\nFACILITATOR_TOKEN=%s\n' "$token"; } > "$tmp_env"
  chmod 600 "$tmp_env"
  mv "$tmp_env" .env
  trap - EXIT INT TERM
  unset token
  echo "created .env from .env.example (MODEL_PROVIDER=mock); the facilitator token is stored in .env (read it there; it is not printed)"
elif ! grep -Eq "$token_pat" .env; then
  echo "warning: .env has no FACILITATOR_TOKEN, so the server is OPEN to anyone who can reach it (see docs/THREAT_MODEL.md)" >&2
fi

if [ "$mode" = "dev" ]; then
  command -v node >/dev/null 2>&1 || die "node is not installed; install Node 22 or newer"
  node_major="$(node -p 'process.versions.node.split(".")[0]')"
  [ "$node_major" -ge 22 ] || die "Node 22 or newer is required (found $(node -v))"
  command -v pnpm >/dev/null 2>&1 || die "pnpm is not installed; run: npm install -g pnpm@9"
  pnpm install
  exec pnpm dev:runtime
fi

command -v docker >/dev/null 2>&1 || die "docker is not installed; install Docker, or use ./run.sh --dev"
docker compose version >/dev/null 2>&1 || die "'docker compose' is not available; install Docker Compose v2, or use ./run.sh --dev"
mkdir -p data
# The container runs as the invoking user so ./data is writable. Never as root: if this script is run as
# root/sudo, fall back to the image's `node` user (1000:1000) unless HOST_UID/HOST_GID were set explicitly.
uid="$(id -u)"
gid="$(id -g)"
if [ "$uid" -eq 0 ] && [ -z "${HOST_UID:-}" ]; then
  echo "warning: running as root; the container will run as 1000:1000 (set HOST_UID/HOST_GID to override; ./data must be writable by that user)" >&2
  uid=1000
  [ -n "${HOST_GID:-}" ] || gid=1000
fi
HOST_UID="${HOST_UID:-$uid}"
HOST_GID="${HOST_GID:-$gid}"
export HOST_UID HOST_GID
exec docker compose -f deploy/compose/docker-compose.yml up --build
