// tests/unit/memory-migrator.test.js
'use strict';
const fs = require('fs');
const path = require('path');
const os = require('os');
const { migrateMemory } = require('../../tools/lib/memory-migrator');

function setupRoot() {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'memmig-'));
  fs.mkdirSync(path.join(tmp, 'docs'), { recursive: true });
  fs.writeFileSync(
    path.join(tmp, 'MEMORY.md'),
    [
      '# MEMORY.md',
      '',
      'Intro.',
      '',
      '---',
      '',
      '## Project Identity',
      '',
      'Project body.',
      '',
      '## GitHub Status Monitoring (Session 41, 2026-05-08)',
      '',
      'Session body.',
      '',
      '## Project Completion Status (as of 2026-05-05 Session 40)',
      '',
      'Snapshot body 40.',
      '',
      '## Project Completion Status (as of 2026-05-03 Session 38)',
      '',
      'Snapshot body 38.',
      '',
      '## Lessons Learned',
      '',
      '- L-9999: Some lesson body.',
      '',
    ].join('\n'),
  );
  fs.writeFileSync(path.join(tmp, 'docs', 'LESSONS.md'), '# LESSONS.md\n');
  fs.writeFileSync(
    path.join(tmp, 'docs', 'ID_REGISTRY.md'),
    [
      '# ID Registry',
      '| Sequence | Next | Last |',
      '| -------- | ---- | ---- |',
      '| Lesson   | L-0055 | L-0054 |',
    ].join('\n'),
  );
  return tmp;
}

describe('migrateMemory', () => {
  test('dry-run reports planned operations without writing files', () => {
    const tmp = setupRoot();
    const result = migrateMemory({ root: tmp, dry: true });
    expect(result.topicFiles.length).toBeGreaterThan(0);
    expect(result.archiveOps.length).toBeGreaterThan(0);
    expect(fs.existsSync(path.join(tmp, 'docs/memory/topics'))).toBe(false);
    fs.rmSync(tmp, { recursive: true, force: true });
  });

  test('full run writes topic files', () => {
    const tmp = setupRoot();
    migrateMemory({ root: tmp, dry: false });
    expect(fs.existsSync(path.join(tmp, 'docs/memory/topics/project-identity.md'))).toBe(true);
    expect(fs.existsSync(path.join(tmp, 'docs/memory/sessions/2026-05-08-github-status-monitoring.md'))).toBe(true);
    expect(fs.existsSync(path.join(tmp, 'docs/memory/snapshots/2026-05-05-project-completion-status.md'))).toBe(true);
    expect(fs.existsSync(path.join(tmp, 'docs/memory/archive/snapshots/2026-05-03-project-completion-status.md'))).toBe(
      true,
    );
    fs.rmSync(tmp, { recursive: true, force: true });
  });

  test('writes regenerated MEMORY.md as compact index (no section bodies)', () => {
    const tmp = setupRoot();
    migrateMemory({ root: tmp, dry: false });
    const m = fs.readFileSync(path.join(tmp, 'MEMORY.md'), 'utf8');
    expect(m).toContain('<!-- generated by tools/memory.js');
    expect(m).toContain('[Project Identity]');
    expect(m).not.toContain('Project body.');
    fs.rmSync(tmp, { recursive: true, force: true });
  });

  test('triages Lessons Learned: orphan L-XXXX appended to LESSONS.md', () => {
    const tmp = setupRoot();
    migrateMemory({ root: tmp, dry: false });
    const lessons = fs.readFileSync(path.join(tmp, 'docs/LESSONS.md'), 'utf8');
    expect(lessons).toContain('L-9999');
    expect(lessons).toContain('migrated from MEMORY.md');
    fs.rmSync(tmp, { recursive: true, force: true });
  });

  test('idempotent no-op when docs/memory/topics exists and is non-empty', () => {
    const tmp = setupRoot();
    migrateMemory({ root: tmp, dry: false });
    const result2 = migrateMemory({ root: tmp, dry: false });
    expect(result2.skipped).toBe(true);
    fs.rmSync(tmp, { recursive: true, force: true });
  });

  test('--force overrides idempotency check', () => {
    const tmp = setupRoot();
    migrateMemory({ root: tmp, dry: false });
    const result2 = migrateMemory({ root: tmp, dry: false, force: true });
    expect(result2.skipped).toBe(false);
    fs.rmSync(tmp, { recursive: true, force: true });
  });
});
