'use strict';
const fs = require('fs');
const path = require('path');
const os = require('os');
const { renderIndex, compactMemory, readEntries } = require('../../tools/lib/memory-index');

describe('renderIndex', () => {
  test('groups by category, sorts sessions/snapshots desc, topics alpha', () => {
    const entries = [
      { category: 'topics', title: 'Technology', file: 'docs/memory/topics/technology.md', date: '2026-04-22' },
      {
        category: 'topics',
        title: 'Project Identity',
        file: 'docs/memory/topics/project-identity.md',
        date: '2026-03-09',
      },
      {
        category: 'sessions',
        title: 'GitHub Status Monitoring',
        file: 'docs/memory/sessions/2026-05-08-github-status-monitoring.md',
        date: '2026-05-08',
      },
      {
        category: 'sessions',
        title: 'Plugin Install',
        file: 'docs/memory/sessions/2026-05-10-plugin-install.md',
        date: '2026-05-10',
      },
      {
        category: 'snapshots',
        title: 'Project Completion Status',
        file: 'docs/memory/snapshots/2026-05-05-project-completion-status.md',
        date: '2026-05-05',
      },
    ];
    const out = renderIndex(entries);
    expect(out).toContain('<!-- generated by tools/memory.js — do not edit by hand -->');
    expect(out).toContain('# MEMORY.md');
    expect(out).toContain('## Topics');
    expect(out).toContain('## Sessions');
    expect(out).toContain('## Snapshots');
    expect(out).toContain('[Project Identity](docs/memory/topics/project-identity.md) · 2026-03-09');
    expect(out.indexOf('Plugin Install')).toBeLessThan(out.indexOf('GitHub Status'));
    expect(out.indexOf('Project Identity')).toBeLessThan(out.indexOf('Technology'));
  });

  test('omits empty category sections', () => {
    const entries = [
      { category: 'topics', title: 'Only One', file: 'docs/memory/topics/only-one.md', date: '2026-05-10' },
    ];
    const out = renderIndex(entries);
    expect(out).toContain('## Topics');
    expect(out).not.toContain('## Sessions');
    expect(out).not.toContain('## Snapshots');
  });

  test('handles empty entries', () => {
    const out = renderIndex([]);
    expect(out).toContain('<!-- generated');
    expect(out).not.toContain('## Topics');
  });
});

describe('compactMemory and readEntries (filesystem)', () => {
  let tmpdir;
  beforeEach(() => {
    tmpdir = fs.mkdtempSync(path.join(os.tmpdir(), 'memidx-'));
    fs.mkdirSync(path.join(tmpdir, 'docs/memory/topics'), { recursive: true });
    fs.mkdirSync(path.join(tmpdir, 'docs/memory/sessions'), { recursive: true });
    fs.mkdirSync(path.join(tmpdir, 'docs/memory/snapshots'), { recursive: true });
  });
  afterEach(() => fs.rmSync(tmpdir, { recursive: true, force: true }));

  test('readEntries reads H1 titles from files', () => {
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/topics/foo.md'), '# Foo Topic\n\nbody\n');
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/sessions/2026-05-10-bar.md'), '# Bar Session\n\nbody\n');
    const entries = readEntries(tmpdir);
    expect(entries).toHaveLength(2);
    const foo = entries.find((e) => e.category === 'topics');
    expect(foo.title).toBe('Foo Topic');
    expect(foo.file).toBe('docs/memory/topics/foo.md');
  });

  test('compactMemory writes MEMORY.md with content from topic files', () => {
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/topics/x.md'), '# X Topic\n\nbody\n');
    compactMemory({ root: tmpdir });
    const content = fs.readFileSync(path.join(tmpdir, 'MEMORY.md'), 'utf8');
    expect(content).toContain('# MEMORY.md');
    expect(content).toContain('[X Topic]');
  });

  test('compactMemory is no-op when docs/memory/ missing', () => {
    const tmp2 = fs.mkdtempSync(path.join(os.tmpdir(), 'memidx-noop-'));
    expect(() => compactMemory({ root: tmp2 })).not.toThrow();
    expect(fs.existsSync(path.join(tmp2, 'MEMORY.md'))).toBe(false);
    fs.rmSync(tmp2, { recursive: true, force: true });
  });

  test('compactMemory skips files in archive/', () => {
    fs.mkdirSync(path.join(tmpdir, 'docs/memory/archive/topics'), { recursive: true });
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/archive/topics/old.md'), '# Old\n\nbody\n');
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/topics/new.md'), '# New\n\nbody\n');
    compactMemory({ root: tmpdir });
    const content = fs.readFileSync(path.join(tmpdir, 'MEMORY.md'), 'utf8');
    expect(content).toContain('[New]');
    expect(content).not.toContain('[Old]');
  });
});

describe('readEntries — complexity + headBody', () => {
  let tmpdir;
  beforeEach(() => {
    tmpdir = fs.mkdtempSync(path.join(os.tmpdir(), 'memidx-c-'));
    fs.mkdirSync(path.join(tmpdir, 'docs/memory/topics'), { recursive: true });
  });
  afterEach(() => fs.rmSync(tmpdir, { recursive: true, force: true }));

  test('parses complexity hint (low/medium/high)', () => {
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/topics/a.md'), '# A\n\n<!-- complexity: high -->\n\nbody\n');
    const entries = readEntries(tmpdir);
    expect(entries[0].complexity).toBe('high');
  });

  test('complexity hint is case-insensitive and whitespace-tolerant', () => {
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/topics/b.md'), '# B\n\n<!--complexity:Low-->\n\nbody\n');
    const entries = readEntries(tmpdir);
    expect(entries[0].complexity).toBe('low');
  });

  test('returns complexity null when no hint present', () => {
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/topics/c.md'), '# C\n\nbody only\n');
    const entries = readEntries(tmpdir);
    expect(entries[0].complexity).toBeNull();
  });

  test('returns headBody (first 5 content lines after H1, skips HTML comment lines)', () => {
    fs.writeFileSync(
      path.join(tmpdir, 'docs/memory/topics/d.md'),
      '# D\n\n<!-- complexity: low -->\n\nline 1\nline 2\nline 3\nline 4\nline 5\nline 6 (excluded)\n',
    );
    const entries = readEntries(tmpdir);
    const lines = entries[0].headBody.split('\n');
    expect(lines).toHaveLength(5);
    expect(lines[0]).toBe('line 1');
    expect(lines[4]).toBe('line 5');
    expect(entries[0].headBody).not.toContain('complexity'); // HTML comment line skipped
    expect(entries[0].headBody).not.toContain('line 6');
  });

  test('treats empty (whitespace-only) lines as non-content', () => {
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/topics/e.md'), '# E\n\nline 1\n\n   \nline 2\nline 3\n');
    const entries = readEntries(tmpdir);
    const lines = entries[0].headBody.split('\n');
    expect(lines.filter((l) => l.trim()).length).toBeLessThanOrEqual(5);
    expect(entries[0].headBody).toContain('line 1');
    expect(entries[0].headBody).toContain('line 2');
  });
});

describe('renderIndex — complexity badges', () => {
  test('includes legend line below intro', () => {
    const out = renderIndex([
      { category: 'topics', title: 'X', file: 'x.md', date: null, complexity: 'low', headBody: '' },
    ]);
    expect(out).toContain('Complexity badges');
    expect(out).toContain('○ low');
    expect(out).toContain('◐ medium');
    expect(out).toContain('● high');
  });

  test('topic with explicit low complexity gets ○ badge', () => {
    const out = renderIndex([
      { category: 'topics', title: 'Low Topic', file: 'low.md', date: null, complexity: 'low' },
    ]);
    expect(out).toContain('- ○ [Low Topic]');
  });

  test('topic with explicit high complexity gets ● badge', () => {
    const out = renderIndex([
      { category: 'topics', title: 'High Topic', file: 'high.md', date: null, complexity: 'high' },
    ]);
    expect(out).toContain('- ● [High Topic]');
  });

  test('topic with no complexity hint gets no badge prefix', () => {
    const out = renderIndex([{ category: 'topics', title: 'No Hint', file: 'nh.md', date: null, complexity: null }]);
    expect(out).toContain('- [No Hint]');
    expect(out).not.toContain('- ○ [No Hint]');
    expect(out).not.toContain('- ◐ [No Hint]');
    expect(out).not.toContain('- ● [No Hint]');
  });

  test('sessions always get ◐ badge regardless of complexity', () => {
    const out = renderIndex([
      { category: 'sessions', title: 'Session 1', file: '2026-01-01-s1.md', date: '2026-01-01', complexity: null },
    ]);
    expect(out).toContain('- ◐ [Session 1]');
  });

  test('snapshots always get ◐ badge regardless of complexity', () => {
    const out = renderIndex([
      { category: 'snapshots', title: 'Snap 1', file: '2026-01-01-s.md', date: '2026-01-01', complexity: null },
    ]);
    expect(out).toContain('- ◐ [Snap 1]');
  });
});
