'use strict';
const { patchClaudeMd } = require('../../tools/lib/memory-claude-md-patcher');

const FIXTURE = [
  '# CLAUDE.md',
  '',
  '## Mandatory Session Startup',
  '',
  '1. Read `AGENTS.md` in full before writing any code or using any tools.',
  '2. Read `MEMORY.md` and all linked topic files.',
  '3. Read `PROMPT_LOG.md` to understand the prompt history.',
  '4. Check `docs/ID_REGISTRY.md` before creating any new artefact.',
  '',
  '## Session Close Checklist',
  '',
  '- [ ] All changes committed to feature branch',
  '- [ ] `MEMORY.md` updated with new learnings',
  '- [ ] `progress.md` updated',
].join('\n');

const IDEMPOTENT_FIXTURE = patchClaudeMd(FIXTURE).text;

describe('patchClaudeMd', () => {
  test('inserts item 3 after "2. Read MEMORY.md" and renumbers subsequent items', () => {
    const { text, changed } = patchClaudeMd(FIXTURE);
    expect(changed).toBe(true);
    const lines = text.split('\n');
    const item3Idx = lines.findIndex((l) => l.startsWith('3. Memory files live'));
    expect(item3Idx).toBeGreaterThan(-1);
    // Old item 3 (PROMPT_LOG) should now be item 4
    const item4Line = lines[item3Idx + 1];
    expect(item4Line).toMatch(/^4\. Read `PROMPT_LOG/);
    // Old item 4 (ID_REGISTRY) should now be item 5
    const item5Line = lines.find((l) => l.match(/^5\./));
    expect(item5Line).toMatch(/^5\. Check `docs\/ID_REGISTRY/);
  });

  test('replaces MEMORY.md checklist line with 4 nested lines', () => {
    const { text } = patchClaudeMd(FIXTURE);
    expect(text).toContain('Memory files updated in `docs/memory/{topics,sessions,snapshots}/`');
    expect(text).not.toContain('`MEMORY.md` updated with new learnings');
    // 4 replacement lines should be present
    const lines = text.split('\n');
    const memoryIdx = lines.findIndex((l) => l.includes('Memory files updated'));
    expect(lines[memoryIdx + 1]).toContain('session learnings');
    expect(lines[memoryIdx + 2]).toContain('stable knowledge');
    expect(lines[memoryIdx + 3]).toContain('Do NOT edit');
  });

  test('is idempotent — returns changed:false if already patched', () => {
    const { changed } = patchClaudeMd(IDEMPOTENT_FIXTURE);
    expect(changed).toBe(false);
  });

  test('idempotent text is unchanged', () => {
    const { text } = patchClaudeMd(IDEMPOTENT_FIXTURE);
    expect(text).toBe(IDEMPOTENT_FIXTURE);
  });

  test('throws if "2. Read MEMORY.md" line not found', () => {
    const broken = FIXTURE.replace('2. Read `MEMORY.md`', '2. Read `NOTES.md`');
    expect(() => patchClaudeMd(broken)).toThrow(/Mandatory Session Startup/);
  });

  test('throws if checklist line does not contain "updated with new learnings"', () => {
    const broken = FIXTURE.replace('`MEMORY.md` updated with new learnings', '`MEMORY.md` updated');
    expect(() => patchClaudeMd(broken)).toThrow(/Session Close Checklist/);
    expect(() => patchClaudeMd(broken)).toThrow(/manual reconciliation required/);
  });
});

describe('patchSuggestModelItem', () => {
  const POST_US0178 = [
    '# CLAUDE.md',
    '',
    '## Mandatory Session Startup',
    '',
    '1. Read `AGENTS.md` in full before writing any code or using any tools.',
    '2. Read `MEMORY.md` and all linked topic files.',
    '3. Memory files live in `docs/memory/{topics,sessions,snapshots}/`. Read `MEMORY.md` (compact index) at session start; read specific topic files when their topic is relevant to the current task. Do not edit `MEMORY.md` directly — it is auto-regenerated by `generate-plan.js`.',
    '4. Read `PROMPT_LOG.md` to understand the prompt history.',
  ].join('\n');

  const { patchSuggestModelItem } = require('../../tools/lib/memory-claude-md-patcher');

  test('inserts new item 4 after US-0178 memory layout item', () => {
    const { text, changed } = patchSuggestModelItem(POST_US0178);
    expect(changed).toBe(true);
    const lines = text.split('\n');
    const item4Idx = lines.findIndex((l) => l.startsWith('4. Before dispatching'));
    expect(item4Idx).toBeGreaterThan(-1);
    expect(lines[item4Idx]).toMatch(/memory:suggest-model/);
  });

  test('renumbers subsequent items', () => {
    const { text } = patchSuggestModelItem(POST_US0178);
    expect(text).toContain('5. Read `PROMPT_LOG.md`');
    expect(text).not.toMatch(/^4\. Read `PROMPT_LOG/m);
  });

  test('is idempotent — second patch is no-op', () => {
    const { text } = patchSuggestModelItem(POST_US0178);
    const { changed } = patchSuggestModelItem(text);
    expect(changed).toBe(false);
  });
});
